In [20]:
#Import Libraries
import pandas as pd
import os
from ydata_profiling import ProfileReport

#Currently, if you run this in codespaces, it doesn't have enough RAM to generate the report. 
skip_report_generation = True

In [21]:
df_historical = pd.read_csv('../Data/Police_Department_Incident_Reports__Historical_2003_to_May_2018.csv')
df_present = pd.read_csv('../Data/Police_Department_Incident_Reports__2018_to_Present.csv')

In [22]:
print(df_present['Incident Category'].unique())

['Recovered Vehicle' 'Larceny Theft' 'Assault' 'Lost Property'
 'Drug Violation' 'Malicious Mischief' 'Drug Offense' 'Non-Criminal'
 'Fraud' 'Warrant' 'Other Offenses' 'Robbery' 'Case Closure'
 'Other Miscellaneous' 'Stolen Property'
 'Offences Against The Family And Children' 'Other' 'Motor Vehicle Theft'
 'Traffic Collision' 'Suspicious Occ' 'Missing Person'
 'Disorderly Conduct' 'Weapons Carrying Etc' 'Rape' 'Burglary'
 'Fire Report' 'Arson' 'Vandalism' 'Suicide' 'Traffic Violation Arrest'
 'Courtesy Report' 'Forgery And Counterfeiting'
 'Miscellaneous Investigation' 'Weapons Offense' 'Embezzlement'
 'Vehicle Misplaced' 'Suspicious' nan 'Homicide' 'Prostitution'
 'Vehicle Impounded' 'Sex Offense' 'Gambling' 'Liquor Laws'
 'Human Trafficking, Commercial Sex Acts' 'Motor Vehicle Theft?'
 'Human Trafficking (A), Commercial Sex Acts' 'Weapons Offence'
 'Civil Sidewalks' 'Human Trafficking (B), Involuntary Servitude']

In [23]:
print(df_historical['Category'].unique())

['ROBBERY' 'VEHICLE THEFT' 'ARSON' 'ASSAULT' 'TRESPASS' 'BURGLARY'
 'LARCENY/THEFT' 'WARRANTS' 'OTHER OFFENSES' 'DRUG/NARCOTIC'
 'SUSPICIOUS OCC' 'LIQUOR LAWS' 'VANDALISM' 'WEAPON LAWS' 'NON-CRIMINAL'
 'MISSING PERSON' 'FRAUD' 'SEX OFFENSES, FORCIBLE' 'SECONDARY CODES'
 'DISORDERLY CONDUCT' 'RECOVERED VEHICLE' 'KIDNAPPING'
 'FORGERY/COUNTERFEITING' 'PROSTITUTION' 'DRUNKENNESS' 'BAD CHECKS'
 'DRIVING UNDER THE INFLUENCE' 'LOITERING' 'STOLEN PROPERTY' 'SUICIDE'
 'BRIBERY' 'EXTORTION' 'EMBEZZLEMENT' 'GAMBLING' 'PORNOGRAPHY/OBSCENE MAT'
 'SEX OFFENSES, NON FORCIBLE' 'TREA']

In [24]:
pd.set_option('display.max_columns', 500)
df_historical.head()

,PdId,IncidntNum,Incident Code,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,location,SF Find Neighborhoods 2 2,Current Police Districts 2 2,Current Supervisor Districts 2 2,Analysis Neighborhoods 2 2,DELETE - Fire Prevention Districts 2 2,DELETE - Police Districts 2 2,DELETE - Supervisor Districts 2 2,DELETE - Zip Codes 2 2,DELETE - Neighborhoods 2 2,DELETE - 2017 Fix It Zones 2 2,Civic Center Harm Reduction Project Boundary 2 2,Fix It Zones as of 2017-11-06 2 2,DELETE - HSOC Zones 2 2,Fix It Zones as of 2018-02-07 2 2,"CBD, BID and GBD Boundaries as of 2017 2 2","Areas of Vulnerability, 2016 2 2",Central Market/Tenderloin Boundary 2 2,Central Market/Tenderloin Boundary Polygon - Updated 2 2,HSOC Zones as of 2018-06-05 2 2,OWED Public Spaces 2 2,Neighborhoods 2
0,4133422003074,41334220,3074,ROBBERY,"ROBBERY, BODILY FORCE",Monday,11/22/2004,17:50,INGLESIDE,NONE,GENEVA AV / SANTOS ST,-122.420084,37.708311,POINT (-122.420084075249 37.7083109744362),NaN,NaN,9.0,NaN,NaN,NaN,8.0,309.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5118535807021,51185358,7021,VEHICLE THEFT,STOLEN AUTOMOBILE,Tuesday,10/18/2005,20:00,PARK,NONE,TURK ST / STJOSEPHS AV,-120.500000,90.000000,POINT (-120.50000000000001 90),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4018830907021,40188309,7021,VEHICLE THEFT,STOLEN AUTOMOBILE,Sunday,02/15/2004,02:00,SOUTHERN,NONE,BRANNAN ST / 1ST ST,-120.500000,90.000000,POINT (-120.50000000000001 90),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11014543126030,110145431,26030,ARSON,ARSON,Friday,02/18/2011,05:27,INGLESIDE,NONE,0 Block of SANJUAN AV,-122.436220,37.724377,POINT (-122.43622001281001 37.7243766140428),94.0,9.0,1.0,28.0,9.0,7.0,6.0,28861.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,94.0
4,10108108004134,101081080,4134,ASSAULT,BATTERY,Sunday,11/21/2010,17:00,SOUTHERN,NONE,400 Block of 10TH ST,-122.410541,37.770913,POINT (-122.410541166987 37.7709130566165),32.0,1.0,10.0,34.0,8.0,2.0,9.0,28853.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,32.0

In [25]:
df_historical = df_historical.drop(columns = ['DELETE - Fire Prevention Districts 2 2', 'DELETE - Police Districts 2 2', 'DELETE - Supervisor Districts 2 2','DELETE - Zip Codes 2 2', 'DELETE - Neighborhoods 2 2','DELETE - 2017 Fix It Zones 2 2','DELETE - HSOC Zones 2 2', 'Civic Center Harm Reduction Project Boundary 2 2', 'Fix It Zones as of 2017-11-06  2 2','Fix It Zones as of 2018-02-07 2 2','CBD, BID and GBD Boundaries as of 2017 2 2','Central Market/Tenderloin Boundary 2 2','Central Market/Tenderloin Boundary Polygon - Updated 2 2','HSOC Zones as of 2018-06-05 2 2','OWED Public Spaces 2 2'])

In [26]:
pd.set_option('display.max_columns', 500)
df_present.head()
#convert historical date time to ['Incident DateTime'], resolution to match
#Delete df_present['Incident Date'] and df_present['Incident Year], Filed online, CAD Number, Report Type Code, Report Type Description, hist Descript, present incident subcategory, present incident description, Address, intersection, CNN, present police district, present supervisor district, present supervisor district 2012, present analysis neighborhood, present, ESNCAG, fix it zones
#rename [Incident Day of Week] to DayOfWeek, Incident Number to IncidntNum, Incident Category  to Category

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,Report Type Code,Report Type Description,Filed Online,Incident Code,Incident Category,Incident Subcategory,Incident Description,Resolution,Intersection,CNN,Police District,Analysis Neighborhood,Supervisor District,Supervisor District 2012,Latitude,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
0,2023/03/13 11:41:00 PM,2023/03/13,23:41,2023,Monday,2023/03/13 11:41:00 PM,125373607041,1253736,230167874,NaN,VS,Vehicle Supplement,NaN,7041,Recovered Vehicle,Recovered Vehicle,"Vehicle, Recovered, Auto",Open or Active,NaN,NaN,Out of SF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023/03/01 05:02:00 AM,2023/03/01,05:02,2023,Wednesday,2023/03/11 03:40:00 PM,125379506374,1253795,236046151,NaN,II,Coplogic Initial,True,6374,Larceny Theft,Larceny Theft - Other,"Theft, Other Property, >$950",Open or Active,NaN,NaN,Mission,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023/03/13 01:16:00 PM,2023/03/13,13:16,2023,Monday,2023/03/13 01:17:00 PM,125357107041,1253571,220343896,NaN,VS,Vehicle Supplement,NaN,7041,Recovered Vehicle,Recovered Vehicle,"Vehicle, Recovered, Auto",Open or Active,NaN,NaN,Out of SF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023/03/13 10:59:00 AM,2023/03/13,10:59,2023,Monday,2023/03/13 11:00:00 AM,125355107041,1253551,230174885,NaN,VS,Vehicle Supplement,NaN,7041,Recovered Vehicle,Recovered Vehicle,"Vehicle, Recovered, Auto",Open or Active,NaN,NaN,Out of SF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023/03/14 06:44:00 PM,2023/03/14,18:44,2023,Tuesday,2023/03/14 06:45:00 PM,125402407041,1254024,230176728,NaN,VS,Vehicle Supplement,NaN,7041,Recovered Vehicle,Recovered Vehicle,"Vehicle, Recovered, Auto",Open or Active,NaN,NaN,Out of SF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df_present = df_present.drop(columns = ['Filed Online', 'CAD Number', 'Report Type Code', 'Report Type Description', 'Incident Subcategory', 'Incident Description', 'Intersection', 'CNN', 'Police District', 'Supervisor District', 'Supervisor District 2012', 'Analysis Neighborhood', 'ESNCAG - Boundary File', 'Central Market/Tenderloin Boundary Polygon - Updated','Civic Center Harm Reduction Project Boundary', 'HSOC Zones as of 2018-06-05', 'Invest In Neighborhoods (IIN) Areas'])

In [28]:
df_present = df_present.rename(columns={"Incident Date": "Date", "Incident Time": "Time", "Incident Day of Week":"DayOfWeek","Incident Number":"IncidntNum","Incident Category":"Category","Latitude":"Y","Longitude":"X"})

In [29]:
#drop null coordinates, incident id, pdid, row id, Analysis Neighborhoods 2 2, Areas of Vulnerability, 2016 2 2, SF Find Neighborhoods 2 2,pd district, incident datetime, incident year, Report Datetime
#rename current police districts and current supervisor districts to remove the 2 2, location to point, neighborhoods 2 to neighborhoods

In [30]:
df_historical.head()

,PdId,IncidntNum,Incident Code,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,location,SF Find Neighborhoods 2 2,Current Police Districts 2 2,Current Supervisor Districts 2 2,Analysis Neighborhoods 2 2,"Areas of Vulnerability, 2016 2 2",Neighborhoods 2
0,4133422003074,41334220,3074,ROBBERY,"ROBBERY, BODILY FORCE",Monday,11/22/2004,17:50,INGLESIDE,NONE,GENEVA AV / SANTOS ST,-122.420084,37.708311,POINT (-122.420084075249 37.7083109744362),NaN,NaN,9.0,NaN,NaN,NaN
1,5118535807021,51185358,7021,VEHICLE THEFT,STOLEN AUTOMOBILE,Tuesday,10/18/2005,20:00,PARK,NONE,TURK ST / STJOSEPHS AV,-120.500000,90.000000,POINT (-120.50000000000001 90),NaN,NaN,NaN,NaN,NaN,NaN
2,4018830907021,40188309,7021,VEHICLE THEFT,STOLEN AUTOMOBILE,Sunday,02/15/2004,02:00,SOUTHERN,NONE,BRANNAN ST / 1ST ST,-120.500000,90.000000,POINT (-120.50000000000001 90),NaN,NaN,NaN,NaN,NaN,NaN
3,11014543126030,110145431,26030,ARSON,ARSON,Friday,02/18/2011,05:27,INGLESIDE,NONE,0 Block of SANJUAN AV,-122.436220,37.724377,POINT (-122.43622001281001 37.7243766140428),94.0,9.0,1.0,28.0,1.0,94.0
4,10108108004134,101081080,4134,ASSAULT,BATTERY,Sunday,11/21/2010,17:00,SOUTHERN,NONE,400 Block of 10TH ST,-122.410541,37.770913,POINT (-122.410541166987 37.7709130566165),32.0,1.0,10.0,34.0,2.0,32.0

In [31]:
df_present = df_present.drop(columns = ['Incident ID','Row ID','Incident Datetime','Incident Year','Report Datetime'])
df_historical = df_historical.drop(columns = ['PdId','Analysis Neighborhoods 2 2','Areas of Vulnerability, 2016 2 2','SF Find Neighborhoods 2 2','PdDistrict'])

In [32]:
#drop Historical descript and historical address
df_historical = df_historical.drop(columns = ['Descript','Address'])
df_historical = df_historical.rename(columns = {'location':'Point','Current Police Districts 2 2':'Current Police Districts','Current Supervisor Districts 2 2':'Current Supervisor Districts','Neighborhoods 2':'Neighborhoods'})

In [33]:
df_historical.isna().sum()

IncidntNum                         0
Incident Code                      0
Category                           0
DayOfWeek                          0
Date                               0
Time                               0
Resolution                         0
X                                  0
Y                                  0
Point                              0
Current Police Districts        1081
Current Supervisor Districts     647
Neighborhoods                   5967
dtype: int64

In [34]:
df_present.isna().sum()

Date                                0
Time                                0
DayOfWeek                           0
IncidntNum                          0
Incident Code                       0
Category                          699
Resolution                          0
Y                               42483
X                               42483
Point                           42483
Neighborhoods                   58080
Current Supervisor Districts    42613
Current Police Districts        43323
dtype: int64

In [35]:
sets = [df_present, df_historical]
df_crime = pd.concat(sets)

In [36]:
df_crime = df_crime.drop(columns = ['Current Supervisor Districts', 'Current Police Districts'])

In [37]:
df_crime = df_crime.dropna(subset=['X','Y'])

In [38]:
df_crime.isna().sum()

Date                 0
Time                 0
DayOfWeek            0
IncidntNum           0
Incident Code        0
Category           685
Resolution           0
Y                    0
X                    0
Point                0
Neighborhoods    21564
dtype: int64

In [39]:
# Keep all related crimes in the Category column
columns =['Larceny Theft', 'Assault', 'Robbery', 'Stolen Property', 'Motor Vehicle Theft', 'Burglary', 'Motor Vehicle Theft?', 
'Human Trafficking (A), Commercial Sex Acts', 'Human Trafficking, Commercial Sex Acts', 'Human Trafficking (B) Involuntary Servitude', 
                'Rape', 'ROBBERY', 'VEHICLE THEFT', 'ASSAULT', 'BURGLARY', 'LARCENY/THEFT', 'KIDNAPPING', 'STOLEN PROPERTY',
               'SEX OFFENSES, FORCIBLE']
df_crime = df_crime[df_crime['Category'].isin(columns)]

In [40]:
df_crime['Category'].unique()

array(['Assault', 'Rape', 'Larceny Theft', 'Robbery', 'Burglary',
       'Motor Vehicle Theft', 'Stolen Property',
       'Human Trafficking, Commercial Sex Acts', 'Motor Vehicle Theft?',
       'Human Trafficking (A), Commercial Sex Acts', 'ROBBERY',
       'VEHICLE THEFT', 'ASSAULT', 'BURGLARY', 'LARCENY/THEFT',
       'SEX OFFENSES, FORCIBLE', 'KIDNAPPING', 'STOLEN PROPERTY'],
      dtype=object)

In [41]:
# Replace similar crimes 

df_crime['Category'] = df_crime['Category'].apply(lambda x: x.replace('Human Trafficking (A), Commercial Sex Acts', 'Kidnapping'))
df_crime['Category'] = df_crime['Category'].apply(lambda x: x.replace('Human Trafficking, Commercial Sex Acts', 'Kidnapping'))
df_crime['Category'] = df_crime['Category'].apply(lambda x: x.replace('Human Trafficking (B), Involuntary Servitude', 'Kidnapping'))
df_crime['Category'] = df_crime['Category'].apply(lambda x: x.replace('Motor Vehicle Theft?', 'Vehicle Theft'))
df_crime['Category'] = df_crime['Category'].apply(lambda x: x.replace('Motor Vehicle Theft', 'Vehicle Theft'))
df_crime['Category'] = df_crime['Category'].apply(lambda x: x.replace('Rape', 'Assault'))
df_crime['Category'] = df_crime['Category'].apply(lambda x: x.replace('Larceny Theft', 'Theft'))
df_crime['Category'] = df_crime['Category'].apply(lambda x: x.replace('SEX OFFENSES, FORCIBLE', 'ASSAULT'))
df_crime['Category'] = df_crime['Category'].apply(lambda x: x.replace('LARCENY/THEFT', 'THEFT'))

In [42]:
df_crime['Category'].unique()

array(['Assault', 'Theft', 'Robbery', 'Burglary', 'Vehicle Theft',
       'Stolen Property', 'Kidnapping', 'ROBBERY', 'VEHICLE THEFT',
       'ASSAULT', 'BURGLARY', 'THEFT', 'KIDNAPPING', 'STOLEN PROPERTY'],
      dtype=object)

In [43]:
# Make the crime categories the same
df_crime['Category'] = df_crime['Category'].str.upper()

In [44]:
df_crime['Category'].unique()

array(['ASSAULT', 'THEFT', 'ROBBERY', 'BURGLARY', 'VEHICLE THEFT',
       'STOLEN PROPERTY', 'KIDNAPPING'], dtype=object)

In [45]:
# Rename X, Y to longitude and latitude
df_crime = df_crime.rename(columns={'Y': 'Latitude', 'X': 'Longitude'})

In [46]:
# Convert to datetime
df_crime['Date'] = pd.to_datetime(df_crime['Date'])

# Add year column
df_crime['Year'] = df_crime['Date'].dt.year

In [47]:
# Spring - March to May
# Summer - June to August
# Autumn - September to November
# Winter - December to February

df_crime['Month'] = df_crime['Date'].dt.month

# add Season column

def map_to_season(month_number):
    if 3 <= month_number <= 5:
        return 'Spring'
    elif 6 <= month_number <= 8:
        return 'Summer'
    elif 9 <= month_number <= 11:
        return 'Fall'
    else:
        return 'Winter'

df_crime['Season'] = df_crime['Month'].apply(map_to_season)

df_crime = df_crime.drop(columns=['Month'])

In [48]:
holidays = [
    # New Year's Day
    '2003-01-01', '2004-01-01', '2005-01-01', '2006-01-01', '2007-01-01',
    '2008-01-01', '2009-01-01', '2010-01-01', '2011-01-01', '2012-01-01',
    '2013-01-01', '2014-01-01', '2015-01-01', '2016-01-01', '2017-01-01',
    '2018-01-01', '2019-01-01', '2020-01-01', '2021-01-01', '2022-01-01',
    '2023-01-01',

    # Christmas
    '2003-12-25', '2004-12-25', '2005-12-25', '2006-12-25', '2007-12-25',
    '2008-12-25', '2009-12-25', '2010-12-25', '2011-12-25', '2012-12-25',
    '2013-12-25', '2014-12-25', '2015-12-25', '2016-12-25', '2017-12-25',
    '2018-12-25', '2019-12-25', '2020-12-25', '2021-12-25', '2022-12-25',
    '2023-12-25',

    # Halloween
    '2003-10-31', '2004-10-31', '2005-10-31', '2006-10-31', '2007-10-31',
    '2008-10-31', '2009-10-31', '2010-10-31', '2011-10-31', '2012-10-31',
    '2013-10-31', '2014-10-31', '2015-10-31', '2016-10-31', '2017-10-31',
    '2018-10-31', '2019-10-31', '2020-10-31', '2021-10-31', '2022-10-31',
    '2023-10-31',

    # Thanksgiving
    '2003-11-27', '2004-11-25', '2005-11-24', '2006-11-23', '2007-11-22',
    '2008-11-27', '2009-11-26', '2010-11-25', '2011-11-24', '2012-11-22',
    '2013-11-28', '2014-11-27', '2015-11-26', '2016-11-24', '2017-11-23',
    '2018-11-22', '2019-11-28', '2020-11-26', '2021-11-25', '2022-11-24',
    '2023-11-23',

    # Memorial Day (Last Monday in May)
    '2003-05-26', '2004-05-31', '2005-05-30', '2006-05-29', '2007-05-28',
    '2008-05-26', '2009-05-25', '2010-05-31', '2011-05-30', '2012-05-28',
    '2013-05-27', '2014-05-26', '2015-05-25', '2016-05-30', '2017-05-29',
    '2018-05-28', '2019-05-27', '2020-05-25', '2021-05-31', '2022-05-30',
    '2023-05-29',

    # Independence Day
    '2003-07-04', '2004-07-04', '2005-07-04', '2006-07-04', '2007-07-04',
    '2008-07-04', '2009-07-04', '2010-07-04', '2011-07-04', '2012-07-04',
    '2013-07-04', '2014-07-04', '2015-07-04', '2016-07-04', '2017-07-04',
    '2018-07-04', '2019-07-04', '2020-07-04', '2021-07-04', '2022-07-04',
    '2023-07-04',

    # Labor Day (First Monday in September)
    '2003-09-01', '2004-09-06', '2005-09-05', '2006-09-04', '2007-09-03',
    '2008-09-01', '2009-09-07', '2010-09-06', '2011-09-05', '2012-09-03',
    '2013-09-02', '2014-09-01', '2015-09-07', '2016-09-05', '2017-09-04',
    '2018-09-03', '2019-09-02', '2020-09-07', '2021-09-06', '2022-09-05',
    '2023-09-04',

    # Veterans' Day
    '2003-11-11', '2004-11-11', '2005-11-11', '2006-11-11', '2007-11-11',
    '2008-11-11', '2009-11-11', '2010-11-11', '2011-11-11', '2012-11-11',
    '2013-11-11', '2014-11-11', '2015-11-11', '2016-11-11', '2017-11-11',
    '2018-11-11', '2019-11-11', '2020-11-11', '2021-11-11', '2022-11-11',
    '2023-11-11'
]

# add isHoliday column
def is_holiday(date):
    return date in holidays

df_crime['isHoliday'] = df_crime['Date'].apply(is_holiday)

In [49]:
# add timeofday column
def map_to_time(hour):
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'

df_crime['Time'] = pd.to_datetime(df_crime['Time'])
df_crime['Hour'] = df_crime['Time'].dt.hour
df_crime['TimeOfDay'] = df_crime['Hour'].apply(map_to_time)

# Drop the 'Hour' column
df_crime = df_crime.drop(columns=['Hour'])

# Removes the date before the time: "2023-10-22 17:50:00" to "17:50:00"
df_crime['Time'] = df_crime['Time'].astype(str).str.split().str[-1]

In [50]:
# add isWeekend column
def weekend_or_not(day):
    return day == "Sunday" or day == "Saturday"

df_crime['isWeekend'] = df_crime['DayOfWeek'].apply(weekend_or_not)

In [51]:
# Rearrange column names for readability
df_crime = df_crime[['Category', 'IncidntNum', 'Incident Code', 'Date', 'Time', 'Year', 'DayOfWeek', 'isWeekend', 'TimeOfDay', 'Season', 'isHoliday', 'Longitude', 'Latitude', 'Point', 'Neighborhoods']]

In [52]:
df_crime.head()

,Category,IncidntNum,Incident Code,Date,Time,Year,DayOfWeek,isWeekend,TimeOfDay,Season,isHoliday,Longitude,Latitude,Point,Neighborhoods
9,ASSAULT,230182844,4134,2023-03-11,14:00:00,2023,Saturday,True,Afternoon,Spring,False,-122.454285,37.772895,POINT (-122.45428511766733 37.772895177200766),NaN
13,ASSAULT,230187101,4134,2023-03-16,17:30:00,2023,Thursday,False,Evening,Spring,False,-122.401324,37.762290,POINT (-122.40132418490647 37.76228996810526),54.0
87,ASSAULT,220435590,4134,2022-07-02,22:53:00,2022,Saturday,True,Night,Summer,False,-122.390020,37.719298,POINT (-122.39001968579463 37.719298464887245),88.0
221,ASSAULT,210426383,4134,2021-07-07,08:18:00,2021,Wednesday,False,Morning,Summer,False,-122.418594,37.753837,POINT (-122.41859394629981 37.753836586731786),53.0
236,ASSAULT,210345909,4134,2021-06-04,09:40:00,2021,Friday,False,Morning,Summer,False,-122.419739,37.785893,POINT (-122.41973873477666 37.78589290013101),20.0